title: nathan chen # name of the site
author: nathan chen # name of site's author
email: nathanielchen8@gmail.com # email of site's author
url:  # root address of the site
description: > # description of the site (multiple lines allowed)
  impressions, not teachings.

permalink: /:slug.html

favicon: "./logo.png" # relative path to site's favicon
# goat_counter: "yoursitename" # put your GoatCounter name if you want to use GoatCounter analytics

remote_theme: riggraz/no-style-please # if you are using GitHub Pages, change it to remote_theme: riggraz/no-style-please

theme_config:
  back_home_text: ".." # customize text for homepage link in post layout
  date_format: "%Y-%m-%d" # customize how date is formatted
  show_description: false # show blog description in home page

sass:
  style: :compressed

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  
collections:
  stories:
    output: true
  poetry:
    output: true
